/* Q10
  write a program to print a series of prime numbers from entered range. ( Take a start and end number
  from a user )
  Perform dry run at least from 10 to 20 …
  Input:-
  Enter starting number: 10
  Enter ending number: 100
  Output:-
  Series = 11 13 17 19 ….. 89 97 */

import java.io.*;
class PrimeNumbers{
	public static void main(String[]args) throws IOException{

		BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
//		BufferedReader br1=new BufferedReader(new InputStreamReader(System.in));
		System.out.print("Enter Starting Number: ");
		int start=Integer.parseInt(br.readLine());
		System.out.print("Enter End Number: ");
		int End=Integer.parseInt(br.readLine());

		if(start<=End){

		for(int i=start;i<=End;i++){
			int count=0;
			for(int j=1;j<=i;j++){
			
				if(i%j==0){
					count++;
				}
				 else{
				 }
			}
				 if(count==2){
					 System.out.print(i);
				 }
				 System.out.print(" ");
			}
		}
		
	}
}









				/*  Perform dry run at least from 10 to 20 …
																																																																																																									                                        Input:-
																																																																																																														                                        Enter starting number: 10
																																																																																																																			                                        Enter ending number: 100
																																																																																																																								                                        Output:-
																																																																																																																													                                        Series = 11 13 17 19 ….. 89 97IIIII  Input:-
																																																																																																																																		                                        Enter starting number: 10
																																																																																																																																							                                        Enter ending number: 100
																																																																																																																																												                                        Output:-
																																																																																																																																																	                                        Series = 11 13 17 19 ….. 89 97Q10
																																																																																																																																																						                                        write a program to print a series of prime numbers from entered range. ( Take a start and end number
																																																																																																																																																													                                                from a user )
																																																																																																																																																											                                        Perform dry run at least from 10 to 20 …
																																																																																																																																																																                                        Input:-
																																																																																																																																																																					                                        Enter starting number: 10
																																																																																																																																																																										                                        Enter ending number: 100
																																																																																																																																																																															                                        Output:-
																																																																																																																																																																																				                                        Series = 11 13 17 19 ….. 89 97Q10
																																																																																																																																																																																									                                        write a program to print a series of prime numbers from entered range. ( Take a start and end number
																																																																																																																																																																																																                                                from a user )
																																																																																																																																																																																														                                        Perform dry run at least from 10 to 20 …
																																																																																																																																																																																																			                                        Input:-
																																																																																																																																																																																																								                                        Enter starting number: 10
																																																																																																																																																																																																													                                        Enter ending number: 100
																																																																																																																																																																																																																		                                        Output:-
																																																																																																																																																																																																																							                                        Series = 11 13 17 19 ….. 89 97Q10
																																																																																																																																																																																																																												                                        write a program to print a series of prime numbers from entered range. ( Take a start and end number
																																																																																																																																																																																																																																			                                                        from a user )
																																																																																																																																																																																																																																	                                        Perform dry run at least from 10 to 20 …
																																																																																																																																																																																																																																						                                        Input:-
																																																																																																																																																																																																																																											                                        Enter starting number: 10
																																																																																																																																																																																																																																																                                        Enter ending number: 100
																																																																																																																																																																																																																																																					                                        Output:-
																																																																																																																																																																																																																																																										                                        Series = 11 13 17 19 ….. 89 97IIIII  Input:-
																																																																																																																																																																																																																																																															                                        Enter starting number: 10
																																																																																																																																																																																																																																																																				                                        Enter ending number: 100
																																																																																																																																																																																																																																																																									                                        Output:-
																																																																																																																																																																																																																																																																														                                        Series = 11 13 17 19 ….. 89 97Q10
																																																																																																																																																																																																																																																																																			                                        write a program to print a series of prime numbers from entered range. ( Take a start and end number
																																																																																																																																																																																																																																																																																										                                                from a user )
																																																																																																																																																																																																																																																																																								                                        Perform dry run at least from 10 to 20 …
																																																																																																																																																																																																																																																																																													                                        Input:-
																																																																																																																																																																																																																																																																																																		                                        Enter starting number: 10
																																																																																																																																																																																																																																																																																																							                                        Enter ending number: 100
																																																																																																																																																																																																																																																																																																												                                        Output:-
																																																																																																																																																																																																																																																																																																																	                                        Series = 11 13 17 19 ….. 89 97Q10
																																																																																																																																																																																																																																																																																																																						                                        write a program to print a series of prime numbers from entered range. ( Take a start and end number
																																																																																																																																																																																																																																																																																																																													                                                from a user )
																																																																																																																																																																																																																																																																																																																											                                        Perform dry run at least from 10 to 20 …
																																																																																																																																																																																																																																																																																																																																                                        Input:-
																																																																																																																																																																																																																																																																																																																																					                                        Enter starting number: 10
																																																																																																																																																																																																																																																																																																																																										                                        Enter ending number: 100
																																																																																																																																																																																																																																																																																																																																															                                        Output:-
																																																																																																																																																																																																																																																																																																																																																				                                        Series = 11 13 17 19 ….. 89 97Q10
																																																																																																																																																																																																																																																																																																																																																									                                        write a program to print a series of prime numbers from entered range. ( Take a start and end number
																																																																																																																																																																																																																																																																																																																																																																                                                        from a user )
																																																																																																																																																																																																																																																																																																																																																														                                        Perform dry run at least from 10 to 20 …
																																																																																																																																																																																																																																																																																																																																																																			                                        Input:-
																																																																																																																																																																																																																																																																																																																																																																								                                        Enter starting number: 10
																																																																																																																																																																																																																																																																																																																																																																													                                        Enter ending number: 100
																																																																																																																																																																																																																																																																																																																																																																																		                                        Output:-
																																																																																																																																																																																																																																																																																																																																																																																							                                        Series = 11 13 17 19 ….. 89 97IIIII  Input:-
																																																																																																																																																																																																																																																																																																																																																																																												                                        Enter starting number: 10
																																																																																																																																																																																																																																																																																																																																																																																																	                                        Enter ending number: 100
																																																																																																																																																																																																																																																																																																																										 
																																																																																																																																																																																																																																																																																																																																																																																																																							                                             
																																																																																																																																																																																																																																																																																																																																																																																																																					                    
																																																																																																																																																																																																																																																																																																																																																																																																																										                                     
																																																																																																																																																																																																																																																																																																																																																																																																																															                                      
																																																																																																																																																																																																																																																																																																																																																																																																																																				                                      
																																																																																																																																																																																																																																																																																																																																																																																																																																									                                       
																																																																																																																																																																																																																																																																																																																																																																																																																																														                                        
																																																																																																																																																																																																																																																																																																																																																																																																																																																			                                       
																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																								                    
																																																																																																																																																																																																																																																																																																																																																																																																																																																													                                        
																																																																																																																																																																																																																																																																																																																																																																																																																																																																		                                  
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																							          
																																																																																																																																																																																																																																																																																																																																																																																																																																														
																																																																																																																																												*/																																																																																																																																																																																																																																																																																						
